version: '3'
services:
  # CONFIGURAÇÕES MYSQL
  db_mysql:
    container_name: db_mysql
    image: mysql:8.0.32-oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    ports:
      - "3336:3306"
    # volumes:
    #   - ./db/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=abc_tech
      - MYSQL_ROOT_PASSWORD=Fiap1234
      
  api:
    container_name: api
    image: spring-boot-api-tutorial-img
    build: app
      # context: ./app
      # dockerfile: Dockerfile
    # depends_on:
    #   - db_mysql
    ports:
      - 8091:5000
    # restart: always
    environment:
      - SERVER_PORT=5000
      - DB_HOSTNAME=db_mysql
      - DB_PORT=3306
      - DB_NAME=abc_tech
      - DB_USER=root
      - DB_PASSWORD=Fiap1234
    tty: true
    volumes:
      - ./app:/app/
